### PR TITLE
Xphi0 change

### PR DESCRIPTION
**Pull request by kkotyk**
I broke git and this needs to be remerged. I added the fix that caused this change to segfault in the first place

### CODE REVIEW

**Comment by egthomas** [comment]
I no longer get the segmentation fault when processing the handful of rawacf files I've tried today.  Should I go ahead and merge this?

**Comment by kkotyk** [comment]
I would say yes. It was a trivial fix.

**Comment by kkotyk** [comment]
As long as the data product seems reasonable and not totally out to lunch of course.

**Comment by egthomas** [comment]
Maybe this is more of a question for Pasha (and unrelated to this particular pull request), but are the velocity errors supposed to still be so small with fitacf.3.0?  

As an example, here's a comparison of CVE data on beam 10 for 20160101 generated using fitacf.2.4 (from rst.3.2), fitacf.2.5 (from the new rst repository), and fitacf.3.0:

fitacf_test_velocity

fitacf_test_error

The velocity errors for the fitacf.3.0 data are pretty much all less than 50 m/s, even for the >300 m/s ionospheric scatter.

**Comment by pasha-ponomarenko** [comment]
This might sound counterintuitive, but velocity errors are not related directly to velocity magntude. Instead, they are proportional to spectral width. It is because velocity values are derived from phase, which is a peculiar parameter, i.e. a subject to 2Pi uncertainty etc. Below are some simulation results for a 1-min itegration time, so one can see that the error is independent of the velocity itself: for a given spectal width of 100 m/s, the error stays the same between  +- 2000 m/s at aseveral m/s. 
[Velocity_err_velocity_simulated.pdf](https://github.com/SuperDARNCanada/fitacf.3.0/files/859867/Velocity_err_velocity_simulated.pdf)
velocity_err_velocity_simulated

In contrast, if you increase spectral width, the errors will grow linearly:
[Velocity_err_width_simulated.pdf](https://github.com/SuperDARNCanada/fitacf.3.0/files/859868/Velocity_err_width_simulated.pdf) 
velocity_err_width_simulated

**Comment by pasha-ponomarenko** [comment]
So, several m/s for velocity errors is reasonable. 
A couple  more things. 
(1) I have changed the minimum number of lags from 3 to 5 in order to be compatible with FITACF2.5. 
(2) I am also concerned a bit about the amount of "salt-and-pepper" velocity values at the edges and wonder if this has any detrimental effect on mapping and how much this would cancel the advantage of getting more points (e.g. like filling the gap in on the lesft side of your example). 
Interestingly, these "fringe" point still show "good" elevaiton values, so we might need to think about different "good data" flags for different parameters.

**Comment by egthomas** [comment]
Thanks for the explanation Pasha - I didn't appreciate the greater dependence of velocity error on spectral width compared to velocity magnitude.  I'll go ahead and merge this pull request so we can move forward with processing and analyzing more data.

**Comment by pasha-ponomarenko** [comment]
In fact, the only dependence on velocity is a casual one owing to the fact that the faster ionospheric scatter echoes usually have larger spectral width. Otherwise, there is no connection whatsoever.

**Pull request merged**
