### PR TITLE
Added a preliminary fit to unwrapped phase. Error is compared to the …

### PR DESCRIPTION
**Pull request by kkotyk**
…fit of the unwrapped phase to determine which offers the best slope estimate

### CODE REVIEW

**Comment by kkotyk** [comment]
@pasha-ponomarenko Compiles and runs. The test here will be from your analysis of plots produced between the fix_unwrap branch and the master branch.

**Comment by egthomas** [comment]
This looks a lot nicer!  Here's a comparison of velocity data from fitacf.2.4, fitacf.2.5, and fitacf.3.0 (using the fix_unwrap branch):

fitacf_test_velocity

All of the vertical velocity streaks have disappeared from the fitacf.3.0 output, nearly all of the salt-and-pepper noise has disappeared, and there appears to be a significant increase in the amount of scatter.

**Comment by egthomas** [comment]
Nevermind, just realized that I was plotting a different beam from what we were looking at in issue #7.  Here is the comparison with the fix_unwrap branch for beam 2:

fitacf_test_velocity

Some of the salt and pepper has disappeared and the ionospheric scatter band from 16-20 UT at ranges 60-85 has filled out, but the vertical velocity streaks and noise on the edge of the ground scatter band are still present.

**Comment by pasha-ponomarenko** [comment]
I still need to test it. This does not look right with respect to the noise above the ground scatter band.  Just compare with my figures from the issue branch, which I have got using IDL version of the unwrapper (https://github.com/SuperDARNCanada/fitacf.3.0/issues/7). I might have missed something while passing the prototype code to Keith, so please hold on.

**Comment by pasha-ponomarenko** [comment]
The results look adequate to the IDL prototype and reduce significantly "salt-and-pepper" noise in low-power scatter echoes, especially at the "tail" of the ground scatter band and fringes of all scatter bands. Importantly, it does not affect velocity magnitude of the ionospheric scatter. 
Before fix:
image
After fix:
image

**Pull request merged**
