### PR TITLE
Additional logging

### PR DESCRIPTION
**Pull request by kkotyk**
This adds some additional code for easier logging. This is needed to be able to see the phase unwrap errors.

### CODE REVIEW

**Comment by pasha-ponomarenko** [comment]
So, does this need any additional testing?

**Comment by kkotyk** [comment]
No, this shouldn't change much. And it can be tested via the fix_unwrap branch. This isnt merging to master.

**Comment by pasha-ponomarenko** [comment]
OK, thats where it is right now! Thanks!

**Comment by kkotyk** [comment]
Can you merge accept this merge into fix_unwrap for me?

**Comment by pasha-ponomarenko** [comment]
Just done it -- must be mind-reading today...

**Pull request merged**
