### PR TITLE
Added the change to use unfitted XCF in set_xcf_phi0

### PR DESCRIPTION
**Pull request by kkotyk**

### CODE REVIEW

**Comment by kkotyk** [comment]
@pasha-ponomarenko look good?

**Comment by pasha-ponomarenko** [comment]
Yep, thanks a lot!

**Comment by kkotyk** [comment]
@pasha-ponomarenko okay, feel free to merge this request then

**Comment by pasha-ponomarenko** [comment]
I might be dumb, but I don't see the green "Merge pull request" button in "This branch has no conflict with the base branch" window above... I have logged in. It just says "Only those with write access to this repository can merge pull requests."

**Review by pasha-ponomarenko — APPROVED** [review]
Approved -- reviewing does not help either. It must be something to do with permissionss...

**Comment by kkotyk** [comment]
Im adding you as a collaborator. We will see if that allows you to merge pull requests.

**Comment by pasha-ponomarenko** [comment]
Thanks, now it worked!
;-)

**Pull request merged**
